### ISSUE TITLE
What.

### ISSUE THREAD

**Issue by 497a** [element-hq/synapse#1]
Just wanted to chime in and say that I'm pretty confused by the changes that have been taken into place. Even though I can see that it was my mistake to use the latest tag of the docker image, I still was quite upset to see that my synapse server 'just stopped working' randomly.

I didn't see any form of announcement that this was gonna happen and to me it looks like this was decided from one moment to the other.

If there was an announcement, I clearly missed it though.

Cheers,
v.d.H.

**Comment by Insert5StarName** [comment]
There was an announcement see https://matrix.org/blog/2023/11/06/future-of-synapse-dendrite/

**Comment by XayOn** [comment]
From that same announcement.

> People who run a Synapse or Dendrite server shouldn’t notice a big change. They’ll need to get their upstream releases from Element’s repositories going forward.

That's definitly not a deprecation notice for the docker images.

If you're going to do so that a simple docker pull will **break** (or, for example, an automatic docker pull...) systems, you should at least try to announce it.

Current docker images are broken, that warrants an announcement (and, probably, set an element-hq docker image repo in DH o GH or both).

**Comment by XayOn** [comment]
It comes, specifically, from this: https://github.com/matrix-org/synapse/commit/e1f8440c8959719a417fbf1bdda11406cfdf523d

Wich is an "updated readme commit" that directly exits with an error instead of passing via a deprecation warning.

The worst thing, is that there's no alternative yet, docker images are not being built anywhere else (as far as I could see), so we docker self-hosters are on our own till further notice.

**Comment by 497a** [comment]
Until the new docker images are working, you can use the `matrixdotorg/synapse:v1.98.0` tag for your homeserver.

**Comment by XayOn** [comment]
>  matrixdotorg/synapse:v1.98.0

Yep, been using that tag since it broke. I don't think that breaking the old images before having the new ones ready is the way to go though...

**Comment by 497a** [comment]
Agreed. I too hope that the new images will be ready as soon as possible.

**Comment by benniekiss** [comment]
from [this announcement](https://element.io/blog/synapse-now-lives-at-github-com-element-hq-synapse/)
> If you’re running an unmodified Synapse, Dendrite, sygnal, sydent, matrix-authentication-service or sliding-sync-proxy, there’s nothing you need to do here other than change any affected GitHub repository URLs from github.com/matrix-org to github.com/element-hq.  Element will start to publish new upstream packages for Debian, Pypi and Dockerhub – but The Matrix.org Foundation will continue to publish mirrors of these packages under the existing names as a convenience to avoid breaking installations.

it seems like this should have been handled better given the most recent announcement from Element.

**Comment by XayOn** [comment]
@benniekiss Yep, from that link:

> but The Matrix.org Foundation will continue to publish mirrors of these packages under the existing names as a convenience to avoid breaking installations.

That didn't go too well...

**Comment by erikjohnston** [comment]
I'm really sorry, breaking the docker images was *not* intentional at all. I've posted a comment on the other issue: https://github.com/element-hq/synapse/issues/2#issuecomment-1856263692

**Comment by ZeroAurora** [comment]
cheers for the transtion! and I wonder if the announcement could be placed in the old repo (since I was very confused and I guess others think so)
