### ISSUE TITLE
Handling Non-Local `user_id` in Room Actions Causes Internal Server Error - validation

### ISSUE THREAD

**Issue by TrevisGordan** [element-hq/synapse#16924]
### Description

I've identified an issue with the  `[POST /_matrix/client/v3/rooms/{roomId}/-action-]` endpoint, where submitting a payload containing a `user_id` from a different home server or an invalid (non-local) user ID results in an Internal Server Error.

The root cause of this issue lies within `roommember.py` in the function `get_local_current_membership_for_user_in_room`, which raises an unhandled standard Exception when encountering a non-local user.

Current exception raising:
```python
if not self.hs.is_mine_id(user_id):
	raise Exception(
		"Cannot call 'get_local_current_membership_for_user_in_room' on "
		"non-local user %s" % (user_id,),
	)
```
(Source: [synapse / get_local_current_membership_for_user_in_room](https://github.com/element-hq/synapse/blob/0621e8eb0eaf20c88b2ebfc07d3a643340093839/synapse/storage/databases/main/roommember.py#L562))

To resolve this issue, I suggest two potential approaches:

1. **Modify the Existing Exception Handling:** Replace the standard Exception within `get_local_current_membership_for_user_in_room` with a `SynapseError`, providing a clear and specific error message to the API consumer. For instance:
   ```python
   message = f"Provided user_id {user_id} is a non-local user"
   raise SynapseError(HTTPStatus.BAD_REQUEST, message, errcode=Codes.M_INVALID_USERNAME)
   ```

2. **Handle the Exception at the Caller Function:** Alternatively, the exception could be caught and handled appropriately within the functions that call `get_local_current_membership_for_user_in_room`, ensuring that a `SynapseError` is raised there instead.

This should improve error handling and user feedback when encountering non-local `user_id`s in room action requests, and better input validation preventing the generic Internal Server Error.

### Steps to reproduce

- Post non local user id to rooms endpoint.
- Reproduce with: 
```shell
curl -X POST -H 'Content-Type: application/json' -d '{"reason": "They'"'"'ve been banned long enough", "user_id": "@cheeky_monkey:ma!trix.org"}' 'http://matrix.localhost/_matrix/client/v3/rooms/!e42d8c:matrix.org/unban?access_token=<TOKEN>'
```

### Homeserver

local

### Synapse Version

1.94.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL

### Workers

Multiple workers

### Platform

K8t

### Relevant log output

```shell
'''
2024-01-31 08:26:30,491 - synapse.http.server - 140 - ERROR - POST-122111 - Failed handle request via 'RoomMembershipRestServlet': <XForwardedForRequest at 0x7fffbe6206d0 method='POST' uri='/_matrix/client/v3/rooms/!e42d8c:matrix.org/unban?access_token=<redacted>' clientproto='HTTP/1.1' site='8083'>
'''
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/synapse/http/server.py", line 326, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/local/lib/python3.9/dist-packages/synapse/http/server.py", line 538, in _async_render
    callback_return = await raw_callback_return
  File "/usr/local/lib/python3.9/dist-packages/synapse/rest/client/room.py", line 1072, in on_POST
    return await self._do(request, requester, room_id, membership_action, None)
  File "/usr/local/lib/python3.9/dist-packages/synapse/rest/client/room.py", line 1045, in _do
    await self.room_member_handler.update_membership(
  File "/usr/local/lib/python3.9/dist-packages/synapse/handlers/room_member.py", line 640, in update_membership
    result = await self.update_membership_locked(
  File "/usr/local/lib/python3.9/dist-packages/synapse/handlers/room_member.py", line 1024, in update_membership_locked
    ) = await self.store.get_local_current_membership_for_user_in_room(
  File "/usr/local/lib/python3.9/dist-packages/synapse/storage/databases/main/roommember.py", line 540, in get_local_current_membership_for_user_in_room
    raise Exception(
Exception: Cannot call 'get_local_current_membership_for_user_in_room' on non-local user @cheeky_monkey:matrix.org
```

**Comment by dklimpel** [comment]
IMO here is Synapse not compliant to the Spec:

https://spec.matrix.org/v1.10/client-server-api/#post_matrixclientv3roomsroomidinvite

> 400 | The request is invalid. A meaningful errcode and description error text will be returned. Example reasons for rejection include:The request body is malformed (errcode set to M_BAD_JSON or M_NOT_JSON).One or more users being invited to the room are residents of a homeserver which does not support the requested room version. The errcode will be M_UNSUPPORTED_ROOM_VERSION in these cases.
> -- | --

The other endpoints do not have a defined error for this.

**Comment by anoadragon453** [comment]
I think Solution 1 is fine. However `M_INVALID_USERNAME` is intended to only be used during registration, [according to the spec](https://spec.matrix.org/v1.10/client-server-api/#other-error-codes). I would instead use `M_BAD_JSON` as @dklimpel suggested.

Note that I think this is only an issue for the following endpoints, which must be completed by a local user:

- [`POST /_matrix/client/v3/rooms/{roomId}/join`](https://spec.matrix.org/v1.10/client-server-api/#post_matrixclientv3roomsroomidjoin)
- [`POST /_matrix/client/v3/rooms/{roomId}/leave`](https://spec.matrix.org/v1.10/client-server-api/#post_matrixclientv3roomsroomidleave)

(`get_local_current_membership_for_user_in_room` is only called in those cases.)

For other actions, such as `/_matrix/client/v3/rooms/{roomId}/unban` in your reproduction example, it's perfectly valid to kick/unban a remote user from a room. If this fails due to the user not being local, then that's a separate bug.

It would also be good to have a regression test which fails on the current codebase, but succeeds after the fix.

**Comment by TrevisGordan** [comment]
@anoadragon453 do you have thoughts on this? ;)

**Comment by anoadragon453** [comment]
Sorry for taking a while to respond to this. I think the diff you posted is sufficient, and suggest going ahead and opening a PR.

In the test, I would have a one check for the a non-local user ID and another for the invalid room ID, instead of including both in a single request. I'd also double-check that the `errcode` is `M_BAD_JSON`.

Thanks!
