### ISSUE TITLE
Element SSL Error on iOS Devices

### ISSUE THREAD

**Issue by VoiletDragon** [element-hq/synapse#17185]
Hi folks,

So recently I have been having issues with Element - Matrix-Synapse on iOS Devices, when trying to play videos that someone has sent me or other people it starts loading the file but it comes up with the following,

An SSL error has occurred and a secure connection cannot be made. 

This is only happening on iOS devices with this message now on Android Devices Videos that are sent or received takes so long to load but eventually they will load. I have noticed a pattern here though, when connected to WIFI on iOS devices it will load the content but outside the network on 4G / 5G this is where all the problems starts.

Matrix-Synapse 1.105.1 
Lets Encrypt SSL handled by Haproxy SSL offloading.

If anyone has any ideas what the problem could be let me know.

**Comment by reivilibre** [comment]
I think this is probably outside of what we can help you with in a Synapse issue.

It sounds like Synapse is working 'fine' and the issue is either in your HAProxy setup, Element iOS or both.

Some suggestions:

- try to look at the HAProxy logs to see what's happening to these requests
    - Synapse's logs might also help a bit, especially at DEBUG level where they will also include when a request *arrives* before it starts to be handled
- try to look at the Element iOS logs if you can — I'm not familiar with iDevices so I don't know how easy this is
- Wireshark and/or tcpdump *might* help you see what's happening
- ask around the Element iOS rooms or issue trackers

Sorry I can't be of more use

Also worth asking in the Synapse Admins room
