### ISSUE TITLE
Per user flag if they can use federation or not?

### ISSUE THREAD

**Issue by darix** [element-hq/synapse#17268]
this might be helpful if you only want to allow a subset of the users to use federation.

would that be much work?

**Comment by anoadragon453** [comment]
Hi @darix. This could already be done today through the use of a Synapse Module.

Such a module could hook into the [`user_may_join_room`](https://element-hq.github.io/synapse/latest/modules/spam_checker_callbacks.html#user_may_join_room) and [`user_may_invite`](https://element-hq.github.io/synapse/latest/modules/spam_checker_callbacks.html#user_may_invite) methods to check whether a user is allowed to join a room over federation or invite remote users to a room. And the [`check_event_for_spam`](https://element-hq.github.io/synapse/latest/modules/spam_checker_callbacks.html#check_event_for_spam) method can be used to ensure a user cannot send or receive messages from remote users, even if they did manage to join a room with remote users in it (perhaps due to them being in such a room before the rules were enforced).

The module could have its own configuration to allow hardcoding the list of users, or reach out to an endpoint to dynamically pull the list. 

Unfortunately I do not know of an available module that does exactly as you want, but writing one would be fairly straightforward, and more flexible than a config option.
