### ISSUE TITLE
unable to make cross networks call 

### ISSUE THREAD

**Issue by Ahmer-rehman** [element-hq/synapse#17624]
I'm experiencing an issue where calls can be successfully made on the same network, but when attempting to make calls across different networks, the call fails. This issue is critical as it restricts the application's functionality in real-world scenarios where users are often on different networks.
Steps to Reproduce:
Connect Device A and Device B to the same network.
Attempt to make a call from Device A to Device B.
Result: The call is successfully established.
Connect Device A to Network X and Device B to a different network.
Attempt to make a call from Device A to Device B.
Result: The call fails to establish.
Expected Behavior: Calls should be successfully established regardless of whether the devices are on the same or different networks.
Actual Behavior: Calls are only successful when both devices are on the same network. Calls fail when devices are on different networks.

**Comment by feroom** [comment]
I hope you are using TURN/COTURN server? 
With what settings?

**Comment by anoadragon453** [comment]
This is not a support forum. Please ask for help in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org). As @feroom says, you likely need to set up a TURN server to allow peers to connect when they are not able to otherwise directly reach each other. See [this documentation](https://element-hq.github.io/synapse/latest/setup/turn/coturn.html#coturn-turn-server).

If you discover a bug is causing this behaviour, then please open a new issue on the relevant repository.
