### ISSUE TITLE
Toggling "Publish this room to the public in matrix.org's room directory" returns 403

### ISSUE THREAD

**Issue by ell1e** [element-hq/synapse#17642]
### Description

Toggling "Publish this room to the public in matrix.org's room directory" returns 403 for any room I try it on. It doesn't look like the room directory is working at all.

### Steps to reproduce

1. Create any regular group chat room on `matrix.org`
2. Try toggling "Publish this room to the public in matrix.org's room directory" in Element
3. The toggle reverts and if you check the network requests you'll see a 403 request

### Homeserver

matrix.org

### Synapse Version

1.114.0rc1 (b=matrix-org-hotfixes,e21bbe9070,dirty)

### Installation Method

I don't know

### Database

whatever runs on matrix.org

### Workers

I don't know

### Platform

whatever runs on matrix.org

### Relevant log output

```shell
I don't have access to the logs
```

**Comment by anoadragon453** [comment]
Hey there @ell1e.

This is intentional as far as I'm aware. Publishing to the room directory is currently disabled on matrix.org out of Trust & Safety concerns. That is their configuration decision.

If you'd like to raise a concern with them, you can contact `support@matrix.org`. We as Synapse maintainers can't do anything about it.
